import mongoengine as me

class Measurement(me.EmbeddedDocument):
    multiplier = me.BooleanField()
    value = me.FloatField(min_value=0)
    unit = me.StringField(choices=['g', 'mg', 'IU', 'μg', 'cal'])

class DietaryRestriction(me.Document):
    name = me.StringField(required=True, primary_key=True)
    excluded_ingredients = me.ListField(me.StringField())
    min_carbs = me.EmbeddedDocumentField(Measurement)
    max_carbs = me.EmbeddedDocumentField(Measurement)
    min_protein = me.EmbeddedDocumentField(Measurement)
    max_protein = me.EmbeddedDocumentField(Measurement)
    min_calories = me.EmbeddedDocumentField(Measurement)
    max_calories= me.EmbeddedDocumentField(Measurement)
    min_fat = me.EmbeddedDocumentField(Measurement)
    max_fat = me.EmbeddedDocumentField(Measurement)
    min_alcohol = me.EmbeddedDocumentField(Measurement)
    max_alcohol = me.EmbeddedDocumentField(Measurement)
    min_caffeine = me.EmbeddedDocumentField(Measurement)
    max_caffeine = me.EmbeddedDocumentField(Measurement)
    min_copper = me.EmbeddedDocumentField(Measurement)
    max_copper = me.EmbeddedDocumentField(Measurement)
    min_calcium = me.EmbeddedDocumentField(Measurement)
    max_calcium = me.EmbeddedDocumentField(Measurement)
    min_chlorine = me.EmbeddedDocumentField(Measurement)
    max_chlorine = me.EmbeddedDocumentField(Measurement)
    min_cholesterol = me.EmbeddedDocumentField(Measurement)
    max_cholesterol = me.EmbeddedDocumentField(Measurement)
    min_fluoride = me.EmbeddedDocumentField(Measurement)
    max_fluoride = me.EmbeddedDocumentField(Measurement)
    min_saturated_fat = me.EmbeddedDocumentField(Measurement)
    max_saturated_fat = me.EmbeddedDocumentField(Measurement)
    min_vitamin_a = me.EmbeddedDocumentField(Measurement)
    max_vitamin_a = me.EmbeddedDocumentField(Measurement)
    min_vitamin_c = me.EmbeddedDocumentField(Measurement)
    max_vitamin_c = me.EmbeddedDocumentField(Measurement)
    min_vitamin_d = me.EmbeddedDocumentField(Measurement)
    max_vitamin_d = me.EmbeddedDocumentField(Measurement)
    min_vitamin_e = me.EmbeddedDocumentField(Measurement)
    max_vitamin_e = me.EmbeddedDocumentField(Measurement)
    min_vitamin_k = me.EmbeddedDocumentField(Measurement)
    max_vitamin_k = me.EmbeddedDocumentField(Measurement)
    min_vitamin_b1 = me.EmbeddedDocumentField(Measurement)
    max_vitamin_b1 = me.EmbeddedDocumentField(Measurement)
    min_vitamin_b2 = me.EmbeddedDocumentField(Measurement)
    max_vitamin_b2 = me.EmbeddedDocumentField(Measurement)
    min_vitamin_b5 = me.EmbeddedDocumentField(Measurement)
    max_vitamin_b5 = me.EmbeddedDocumentField(Measurement)
    min_vitamin_b3 = me.EmbeddedDocumentField(Measurement)
    max_vitamin_b3 = me.EmbeddedDocumentField(Measurement)
    min_vitamin_b6 = me.EmbeddedDocumentField(Measurement)
    max_vitamin_b6 = me.EmbeddedDocumentField(Measurement)
    min_vitamin_b12 = me.EmbeddedDocumentField(Measurement)
    max_vitamin_b12 = me.EmbeddedDocumentField(Measurement)
    min_fiber = me.EmbeddedDocumentField(Measurement)
    max_fiber = me.EmbeddedDocumentField(Measurement)
    min_folate = me.EmbeddedDocumentField(Measurement)
    max_folate = me.EmbeddedDocumentField(Measurement)
    min_folic_acid = me.EmbeddedDocumentField(Measurement)
    max_folic_acid = me.EmbeddedDocumentField(Measurement)
    min_iodine = me.EmbeddedDocumentField(Measurement)
    max_iodine = me.EmbeddedDocumentField(Measurement)
    min_iron = me.EmbeddedDocumentField(Measurement)
    max_iron = me.EmbeddedDocumentField(Measurement)
    min_magnesium = me.EmbeddedDocumentField(Measurement)
    max_magnesium = me.EmbeddedDocumentField(Measurement)
    min_manganese = me.EmbeddedDocumentField(Measurement)
    max_manganese = me.EmbeddedDocumentField(Measurement)
    min_phosphorus = me.EmbeddedDocumentField(Measurement)
    max_phosphorus = me.EmbeddedDocumentField(Measurement)
    min_potassium = me.EmbeddedDocumentField(Measurement)
    max_potassium = me.EmbeddedDocumentField(Measurement)
    min_selenium = me.EmbeddedDocumentField(Measurement)
    max_selenium = me.EmbeddedDocumentField(Measurement)
    min_sodium = me.EmbeddedDocumentField(Measurement)
    max_sodium = me.EmbeddedDocumentField(Measurement)
    min_sugar = me.EmbeddedDocumentField(Measurement)
    max_sugar = me.EmbeddedDocumentField(Measurement)
    min_zinc = me.EmbeddedDocumentField(Measurement)
    max_zinc = me.EmbeddedDocumentField(Measurement)